export const DEPARTMENTS = [{
        id: "Dept01",
        name: "Trà sữa",
        numberOfProduct: 21,
        img: '/assets/images/tsbongdem.jpg',
        imgdep: '/assets/images/depTrasua.png',
    },
    {
        id: "Dept02",
        name: "Đồ ăn vặt",
        numberOfProduct: 15,
        img: '/assets/images/banhtrangcuon.jpg',
        imgdep: '/assets/images/depFood.png',

    },
    {
        id: "Dept03",
        name: "Nước hoa quả",
        numberOfProduct: 7,
        img: '/assets/images/nuocephoaqua.jpg',
        imgdep: '/assets/images/depHoaqua.png',
    },
    {
        id: "Dept04",
        name: "Soda",
        numberOfProduct: 7,
        img: '/assets/images/soda.jpg',
        imgdep: '/assets/images/depSoda.png',
    },
    {
        id: "Dept05",
        name: "Sinh tố",
        numberOfProduct: 5,
        img: '/assets/images/sinhto.jpg',
        imgdep: '/assets/images/depSinhto.png',
    },
    {
        id: "Dept06",
        name: "Coffee and Tea",
        numberOfProduct: 6,
        img: '/assets/images/coffe.jpg',
        imgdep: '/assets/images/depCaphe.png',
    },
    {
        id: "Dept07",
        name: "Sữa chua",
        numberOfProduct: 10,
        img: '/assets/images/scdautay.jpg',
        imgdep: '/assets/images/depSC.png',
    },
    {
        id: "Dept08",
        name: "Trà tranh",
        numberOfProduct: 8,
        img: '/assets/images/tradao.jpg',
        imgdep: '/assets/images/depTratranh.png',
    },
    {
        id: "Dept09",
        name: "Sữa tươi mix vị",
        numberOfProduct: 4,
        img: '/assets/images/mixvi.jpg',
        imgdep: '/assets/images/depMixvi.png',
    },
    {
        id: "Dept10",
        name: "Đồ đá xay",
        numberOfProduct: 4,
        img: '/assets/images/matchadaxoay.jpg',
        imgdep: '/assets/images/depDodaxay.png',
    }
]


export const PRODUCTS = [{
        id: 0,
        name: "Bánh Flan kem trứng",
        price: 8000,
        department: DEPARTMENTS[1],
        image: '/assets/images/banhflankemtrung.jpg',
    },
    {
        id: 1,
        name: "Sữa tươi xốt xoài",
        price: 25000,
        department: DEPARTMENTS[8],
        image: '/assets/images/suatuoisotxoai.jpg',
    },
    {
        id: 2,
        name: "Bánh tráng cuốn",
        price: 20000,
        department: DEPARTMENTS[1],
        image: '/assets/images/banhtrangcuon.jpg',
    },
    {
        id: 3,
        name: "Sữa chua dâu tây",
        price: 25000,
        department: DEPARTMENTS[6],
        image: '/assets/images/scdautay.jpg',
    },
    {
        id: 4,
        name: "Bánh tráng trộn",
        price: 15000,
        department: DEPARTMENTS[1],
        image: '/assets/images/banhtrangtron.jpg',
    },
    {
        id: 5,
        name: "Chocolate cốt dừa",
        price: 25000,
        department: DEPARTMENTS[2],
        image: '/assets/images/socolacotdua.jpg',
    },
    {
        id: 6,
        name: "Trà đào cam xả",
        price: 25000,
        department: DEPARTMENTS[5],
        image: '/assets/images/tradao.jpg',
    },
    {
        id: 7,
        name: "Trà sữa bóng đêm kem trứng cháy",
        price: 32000,
        department: DEPARTMENTS[0],
        image: '/assets/images/tsbongdem.jpg',
    },
    {
        id: 8,
        name: "Trà sữa TC hoa đậu biếc",
        price: 30000,
        department: DEPARTMENTS[0],
        image: '/assets/images/tshoadaubiec.jpg',
    },
    {
        id: 9,
        name: "Matcha đá xay",
        price: 25000,
        department: DEPARTMENTS[0],
        image: '/assets/images/matchadaxoay.jpg',
    },
    {
        id: 10,
        name: "Sữa chua việt quất",
        price: 25000,
        department: DEPARTMENTS[6],
        image: '/assets/images/scvietquat.jpg',
    },


]